# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/lowresgamr/Documents/Data Structures/Programming assignment 1"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/lowresgamr/Documents/Data Structures/Programming assignment 1"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/lowresgamr/Documents/Data Structures/Programming assignment 1/CMakeFiles" "/home/lowresgamr/Documents/Data Structures/Programming assignment 1//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/lowresgamr/Documents/Data Structures/Programming assignment 1/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stars

# Build rule for target.
stars: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stars
.PHONY : stars

# fast build rule for target.
stars/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stars.dir/build.make CMakeFiles/stars.dir/build
.PHONY : stars/fast

#=============================================================================
# Target rules for targets named stars.exe

# Build rule for target.
stars.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stars.exe
.PHONY : stars.exe

# fast build rule for target.
stars.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stars.exe.dir/build.make CMakeFiles/stars.exe.dir/build
.PHONY : stars.exe/fast

stars.o: stars.cpp.o
.PHONY : stars.o

# target to build an object file
stars.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stars.dir/build.make CMakeFiles/stars.dir/stars.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stars.exe.dir/build.make CMakeFiles/stars.exe.dir/stars.cpp.o
.PHONY : stars.cpp.o

stars.i: stars.cpp.i
.PHONY : stars.i

# target to preprocess a source file
stars.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stars.dir/build.make CMakeFiles/stars.dir/stars.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stars.exe.dir/build.make CMakeFiles/stars.exe.dir/stars.cpp.i
.PHONY : stars.cpp.i

stars.s: stars.cpp.s
.PHONY : stars.s

# target to generate assembly for a file
stars.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stars.dir/build.make CMakeFiles/stars.dir/stars.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stars.exe.dir/build.make CMakeFiles/stars.exe.dir/stars.cpp.s
.PHONY : stars.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stars"
	@echo "... stars.exe"
	@echo "... stars.o"
	@echo "... stars.i"
	@echo "... stars.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

